from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Text, Float, Boolean,
    DateTime, JSON, ForeignKey, Index, create_engine,
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker
from sqlalchemy.pool import StaticPool
 
Base = declarative_base()
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Event Model
# ─────────────────────────────────────────────────────────────────────────────
class Event(Base):
    """Raw security event ingested from any log source."""
    __tablename__ = "events"
 
    id           = Column(Integer, primary_key=True, autoincrement=True)
    timestamp    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    source_ip    = Column(String(45), index=True)
    dest_ip      = Column(String(45))
    source_port  = Column(Integer)
    dest_port    = Column(Integer)
    protocol     = Column(String(10))
    source_type  = Column(String(50), index=True)   # syslog / filebeat / netflow
    category     = Column(String(50), index=True)   # auth / network / malware
    severity     = Column(String(20), index=True)
    severity_num = Column(Integer, default=1)
    raw_message  = Column(Text)
    parsed_data  = Column(JSON)
    hostname     = Column(String(255), index=True)
    username     = Column(String(255))
    process_name = Column(String(255))
    geo_country  = Column(String(100))
    geo_city     = Column(String(100))
    geo_lat      = Column(Float)
    geo_lon      = Column(Float)
    is_threat_ip = Column(Boolean, default=False)
    tags         = Column(JSON)          # list of strings
    rule_matches = Column(JSON)          # matched rule IDs
 
  
    alert_id     = Column(Integer, ForeignKey("alerts.id"), nullable=True)
    alert        = relationship("Alert", back_populates="events")
 
    __table_args__ = (
        Index("ix_events_ts_severity", "timestamp", "severity"),
        Index("ix_events_src_ip_ts",   "source_ip",  "timestamp"),
    )
 
    def to_dict(self):
        return {
            "id":           self.id,
            "timestamp":    self.timestamp.isoformat() if self.timestamp else None,
            "source_ip":    self.source_ip,
            "dest_ip":      self.dest_ip,
            "source_port":  self.source_port,
            "dest_port":    self.dest_port,
            "protocol":     self.protocol,
            "source_type":  self.source_type,
            "category":     self.category,
            "severity":     self.severity,
            "severity_num": self.severity_num,
            "raw_message":  self.raw_message,
            "parsed_data":  self.parsed_data,
            "hostname":     self.hostname,
            "username":     self.username,
            "process_name": self.process_name,
            "geo_country":  self.geo_country,
            "geo_city":     self.geo_city,
            "geo_lat":      self.geo_lat,
            "geo_lon":      self.geo_lon,
            "is_threat_ip": self.is_threat_ip,
            "tags":         self.tags,
            "rule_matches": self.rule_matches,
            "alert_id":     self.alert_id,
        }
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Alert Model
# ─────────────────────────────────────────────────────────────────────────────
class Alert(Base):
    """Correlated alert generated by detection rules."""
    __tablename__ = "alerts"
 
    id             = Column(Integer, primary_key=True, autoincrement=True)
    timestamp      = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at     = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    title          = Column(String(500), nullable=False)
    description    = Column(Text)
    severity       = Column(String(20),  nullable=False, index=True)
    severity_num   = Column(Integer, default=1)
    rule_id        = Column(String(50),  index=True)
    rule_name      = Column(String(255))
    category       = Column(String(50),  index=True)
    source_ip      = Column(String(45),  index=True)
    dest_ip        = Column(String(45))
    hostname       = Column(String(255))
    username       = Column(String(255))
    status         = Column(String(20), default="OPEN", index=True)  # OPEN/ACK/CLOSED/FP
    analyst_notes  = Column(Text)
    event_count    = Column(Integer, default=1)
    mitre_tactic   = Column(String(100))
    mitre_tech     = Column(String(100))
    ioc_list       = Column(JSON)
    tags           = Column(JSON)
    notified       = Column(Boolean, default=False)
    false_positive = Column(Boolean, default=False)
 
    events = relationship("Event", back_populates="alert")
 
    __table_args__ = (
        Index("ix_alerts_severity_status", "severity", "status"),
    )
 
    def to_dict(self):
        return {
            "id":             self.id,
            "timestamp":      self.timestamp.isoformat() if self.timestamp else None,
            "updated_at":     self.updated_at.isoformat() if self.updated_at else None,
            "title":          self.title,
            "description":    self.description,
            "severity":       self.severity,
            "severity_num":   self.severity_num,
            "rule_id":        self.rule_id,
            "rule_name":      self.rule_name,
            "category":       self.category,
            "source_ip":      self.source_ip,
            "dest_ip":        self.dest_ip,
            "hostname":       self.hostname,
            "username":       self.username,
            "status":         self.status,
            "analyst_notes":  self.analyst_notes,
            "event_count":    self.event_count,
            "mitre_tactic":   self.mitre_tactic,
            "mitre_tech":     self.mitre_tech,
            "ioc_list":       self.ioc_list,
            "tags":           self.tags,
            "false_positive":  self.false_positive,
        }
 
 
# ─────────────────────────────────────────────────────────────────────────────
# Asset Model
# ─────────────────────────────────────────────────────────────────────────────
class Asset(Base):
    """Known network asset / host."""
    __tablename__ = "assets"
 
    id          = Column(Integer, primary_key=True, autoincrement=True)
    ip_address  = Column(String(45), unique=True, nullable=False, index=True)
    hostname    = Column(String(255))
    mac_address = Column(String(17))
    os_type     = Column(String(100))
    asset_type  = Column(String(50))   # server / workstation / network / iot
    criticality = Column(String(20),  default="MEDIUM")  # LOW/MEDIUM/HIGH/CRITICAL
    owner       = Column(String(255))
    department  = Column(String(255))
    location    = Column(String(255))
    first_seen  = Column(DateTime, default=datetime.utcnow)
    last_seen   = Column(DateTime, default=datetime.utcnow)
    open_ports  = Column(JSON)
    tags        = Column(JSON)
    notes       = Column(Text)
    alert_count = Column(Integer, default=0)
    risk_score  = Column(Float,   default=0.0)
 
    def to_dict(self):
        return {
            "id":          self.id,
            "ip_address":  self.ip_address,
            "hostname":    self.hostname,
            "asset_type":  self.asset_type,
            "criticality": self.criticality,
            "owner":       self.owner,
            "department":  self.department,
            "first_seen":  self.first_seen.isoformat() if self.first_seen else None,
            "last_seen":   self.last_seen.isoformat() if self.last_seen else None,
            "open_ports":  self.open_ports,
            "tags":        self.tags,
            "alert_count": self.alert_count,
            "risk_score":  self.risk_score,
        }
 
 
# ─────────────────────────────────────────────────────────────────────────────
# ThreatIntel Model
# ─────────────────────────────────────────────────────────────────────────────
class ThreatIntel(Base):
    """Threat intelligence indicators (IPs, domains, hashes, URLs)."""
    __tablename__ = "threat_intel"
 
    id          = Column(Integer, primary_key=True, autoincrement=True)
    indicator   = Column(String(500), nullable=False, index=True)
    ioc_type    = Column(String(50))    # ip / domain / hash / url / email
    threat_type = Column(String(100))   # malware / c2 / phishing / scanner
    severity    = Column(String(20),  default="HIGH")
    confidence  = Column(Integer,     default=80)   # 0–100
    source      = Column(String(255))
    first_seen  = Column(DateTime, default=datetime.utcnow)
    last_seen   = Column(DateTime, default=datetime.utcnow)
    expires_at  = Column(DateTime)
    tags        = Column(JSON)
    description = Column(Text)
    active      = Column(Boolean, default=True)
 
    def to_dict(self):
        return {
            "id":          self.id,
            "indicator":   self.indicator,
            "ioc_type":    self.ioc_type,
            "threat_type": self.threat_type,
            "severity":    self.severity,
            "confidence":  self.confidence,
            "source":      self.source,
            "first_seen":  self.first_seen.isoformat() if self.first_seen else None,
            "last_seen":   self.last_seen.isoformat() if self.last_seen else None,
            "active":      self.active,
        }
 
 
# ─────────────────────────────────────────────────────────────────────────────
# AuditLog Model
# ─────────────────────────────────────────────────────────────────────────────
class AuditLog(Base):
    """Audit trail for every analyst action."""
    __tablename__ = "audit_logs"
 
    id         = Column(Integer, primary_key=True, autoincrement=True)
    timestamp  = Column(DateTime, default=datetime.utcnow, index=True)
    action     = Column(String(100))
    entity     = Column(String(50))
    entity_id  = Column(Integer)
    analyst    = Column(String(100), default="system")
    details    = Column(JSON)
    ip_address = Column(String(45))
 
    def to_dict(self):
        return {
            "id":        self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "action":    self.action,
            "entity":    self.entity,
            "entity_id": self.entity_id,
            "analyst":   self.analyst,
            "details":   self.details,
        }
 
 
# ─────────────────────────────────────────────────────────────────────────────
# DB Helpers
# ─────────────────────────────────────────────────────────────────────────────
def get_engine(db_url: str):
    """SQLite aur PostgreSQL dono support karta hai."""
    if "sqlite" in db_url:
        return create_engine(
            db_url,
            connect_args={"check_same_thread": False},
            poolclass=StaticPool,
        )
    return create_engine(db_url, pool_pre_ping=True)
 
 
def init_db(db_url: str):
    engine = get_engine(db_url)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    return engine, Session
